// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6yIdKlHnif9uyzJUgTjmOsWykVcpXd1o',
    appId: '1:116365295074:web:bb90d6a2686fcac61a0dbb',
    messagingSenderId: '116365295074',
    projectId: 'fir-flutter-codelab-87eec',
    authDomain: 'fir-flutter-codelab-87eec.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-87eec.firebasestorage.app',
    measurementId: 'G-P6R4KP7YEH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGAVcX72lAnLctRiBOTq9L1XVZzexAnuI',
    appId: '1:116365295074:android:2458a4f638e377b01a0dbb',
    messagingSenderId: '116365295074',
    projectId: 'fir-flutter-codelab-87eec',
    storageBucket: 'fir-flutter-codelab-87eec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0tgRQNk2xTPVCu-VJPAgc0aYN2KiqEzE',
    appId: '1:116365295074:ios:01406818d42424b51a0dbb',
    messagingSenderId: '116365295074',
    projectId: 'fir-flutter-codelab-87eec',
    storageBucket: 'fir-flutter-codelab-87eec.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0tgRQNk2xTPVCu-VJPAgc0aYN2KiqEzE',
    appId: '1:116365295074:ios:01406818d42424b51a0dbb',
    messagingSenderId: '116365295074',
    projectId: 'fir-flutter-codelab-87eec',
    storageBucket: 'fir-flutter-codelab-87eec.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
